- .github/workflows/github-actions.yml
- Dockerfile
- build.gradle
> Feat : DockerComposeFile 세팅

- build.gradle
- src/main/java/com/example/catchroom_be/CatchRoomBeApplication.java
- src/main/resources/LogBack.xml
- src/main/resources/application.yml
> Refact : 에러 테스트

- src/main/java/com/example/catchroom_be/CatchRoomBeApplication.java
- src/main/java/com/example/catchroom_be/User/controller/OAuthController.java
- src/main/java/com/example/catchroom_be/global/common/ApiResponse.java
- src/main/java/com/example/catchroom_be/global/common/BaseTime.java
- src/main/java/com/example/catchroom_be/global/exception/BaseException.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorMessage.java
- src/main/java/com/example/catchroom_be/global/exception/GlobalExceptionHandler.java
- src/main/java/com/example/catchroom_be/global/exception/SuccessMessage.java
> Feat : 에러코드 및 반환 타입 설정

- src/main/java/com/example/catchroom_be/domain/accommodation/entity/Accommodation.java
- src/main/java/com/example/catchroom_be/domain/accommodation/entity/AccommodationImage.java
- src/main/java/com/example/catchroom_be/domain/accommodation/entity/Room.java
- src/main/java/com/example/catchroom_be/domain/accommodation/entity/RoomImage.java
- src/main/java/com/example/catchroom_be/domain/accommodation/repository/AccommodationImageRepository.java
- src/main/java/com/example/catchroom_be/domain/accommodation/repository/AccommodationRepository.java
- src/main/java/com/example/catchroom_be/domain/accommodation/repository/RoomImageRepository.java
- src/main/java/com/example/catchroom_be/domain/accommodation/repository/RoomRepository.java
- src/main/java/com/example/catchroom_be/domain/accommodation/type/AccommodationType.java
- src/main/java/com/example/catchroom_be/domain/accommodation/type/TransportationType.java
> Feat : 숙소, 객실 엔티티 도메인 설정

- src/main/java/com/example/catchroom_be/domain/product/entity/OrderHistory.java
- src/main/java/com/example/catchroom_be/domain/product/repository/OrderHistoryRepository.java
- src/main/java/com/example/catchroom_be/domain/product/service/OrderHistoryService.java
- src/main/java/com/example/catchroom_be/domain/product/type/TransportationType.java
- src/main/java/com/example/catchroom_be/domain/test_user/entity/UserTest.java
- src/main/java/com/example/catchroom_be/domain/test_user/repository/UserTestRepository.java
- src/main/java/com/example/catchroom_be/domain/test_user/service/UserTestService.java
UserTest 를 만들었고, OrderHistory를 만들었습니다. 
계정 3개 정도 만들었어요
> Feat : OrderHistory, UserTest 작업

- src/main/java/com/example/catchroom_be/domain/accommodation/controller/AccommodationController.java
- src/main/java/com/example/catchroom_be/domain/accommodation/dto/response/AccommodationResponse.java
- src/main/java/com/example/catchroom_be/domain/accommodation/dto/response/RoomResponse.java
- src/main/java/com/example/catchroom_be/domain/accommodation/exception/AccommodationException.java
- src/main/java/com/example/catchroom_be/domain/accommodation/repository/AccommodationRepository.java
- src/main/java/com/example/catchroom_be/domain/accommodation/repository/RoomRepository.java
- src/main/java/com/example/catchroom_be/domain/accommodation/service/AccommodationService.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
채팅 서버에 테스트 해볼 숙소 & 객실 정보를 얻어오는 api 개발하였습니다. 
어떤 변경 사항이 있나요?
> Feat : Accommodation Controller 작업

- src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/dto/OrderHistoryCandidateResponse.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/repository/OrderHistoryRepository.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
- 야놀자 매물 중 판매할 숙박권 후보 리스트 조회 로직 추가
- userDetailsService 코드 생성 후 인가 조회 기능 추가 예정
어떤 변경 사항이 있나요?
> Feat : OrderHistory 도메인 추가

- src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
- src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleGetDetailInfoResponse.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- src/main/java/com/example/catchroom_be/domain/product/type/DealState.java
- 야놀자 매물 중 판매할 숙박권 선택 시 해당 매물 정보 응답
어떤 변경 사항이 있나요?
> Feat : 판매할 숙박권 상세 조회 로직

- .gitignore
- src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
- src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleRegistResponse.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- src/main/java/com/example/catchroom_be/global/config/JwtFilterConfig.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- src/main/resources/application.yml
- 사용자가 선택한 야놀자 매물을 판매하기 위한 정보 등록
- 시큐리티 코드 완성 후 사용자 인가 확인 로직 추가 예정
- gitIgnore에 application.ym
어떤 변경 사항이 있나요?
> Feature/#32 상품등록

- src/main/java/com/example/catchroom_be/domain/user/controller/MeController.java
- src/main/java/com/example/catchroom_be/domain/user/dto/request/RegisterRequest.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/JwtEntryPoint.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeEmailService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeJWTService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeLoginService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeNickNameService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
- src/main/java/com/example/catchroom_be/global/config/JwtFilterConfig.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- src/main/java/com/example/catchroom_be/global/exception/GlobalExceptionHandler.java
- 회원/로그인 API 개발 완료
어떤 변경 사항이 있나요?
- [v] 새로운 기능 추가
- [v] 버그 수정
- [v ] 주석 추가 및 수정
- [v ] 파일 혹은 폴더 삭제
- [v] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.)
- [v] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
> Refact : 회원/로그인 개발 완료

- src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleEditRequest.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleEditResponse.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- 판매할 숙박권(product) id 및 수정 내용 전달 시 수정 진행
- 수정한 내용만 전달하는 것이 아닌, 등록 시 요청한 등록 포맷에 수정한 내용을 담아 그대로 요청 필요
어떤 변경 사항이 있나요?
> Feat : 판매 숙박권(상품) 수정 로직 추가

- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
> Refact : 긴급 수정

- src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/repository/OrderHistoryRepository.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
- src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- src/main/java/com/example/catchroom_be/global/config/JwtFilterConfig.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- 판매할 숙박권(product) id 및 수정 내용 전달 시 삭제 진행
- 삭제 시 orderHistory(야놀자매물)의 is_sale 칼럼 false로 복귀
- 숙박권 등록 시 orderHistory(야놀자매물)의 is_sale 칼럼 true로 변환
어떤 변경 사항이 있나요?
> Feature/#34 상품삭제

- src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleEditRequest.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
> Feat : 판매할 숙박권(상품) 등록 시 LocalDate 타입 변경

- src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/repository/OrderHistoryRepository.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
- src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleEditRequest.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleEditResponse.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- src/main/java/com/example/catchroom_be/domain/user/controller/MeController.java
- src/main/java/com/example/catchroom_be/global/config/JwtFilterConfig.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
> Refact : 회원/로그인 핫픽스

- src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
- src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
- src/main/java/com/example/catchroom_be/global/config/JwtFilterConfig.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- JWT필터에 걸리지 않도록 인가 처리 진행(이후 삭제 예정)
어떤 변경 사항이 있나요?
> Refactor : 판매 숙박권 리스트 조회/상세조회 인가 임시처리

- src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/dto/OrderHistoryCandidateResponse.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
- src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
- src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
- src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- @AuthenticationPrincipal 활용
어떤 변경 사항이 있나요?
> Refactor : 판매 도메인 API 내 회원 인가처리 추가

- src/main/resources/application.yml
This reverts commit a15676d6b37483012424e015057bb6d828b6945d.
어떤 변경 사항이 있나요?
> Revert "fixed untracked files"

- src/main/resources/application.yml
> Refact : 코드 수정

- src/main/resources/application.yml
> Refact : 버그 수정

- src/main/java/com/example/catchroom_be/domain/user/controller/mypage/MyPageController.java
- src/main/java/com/example/catchroom_be/domain/user/controller/user/MeController.java
- src/main/java/com/example/catchroom_be/domain/user/entity/User.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeAccessTokenService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeLoginService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageLogOutService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageProfileService.java
- src/main/java/com/example/catchroom_be/global/config/RedisConfig.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
- src/main/java/com/example/catchroom_be/global/jwt/config/JwtFilterConfig.java
- src/main/java/com/example/catchroom_be/global/jwt/dto/JwtPayload.java
- src/main/java/com/example/catchroom_be/global/jwt/dto/RefreshToken.java
- src/main/java/com/example/catchroom_be/global/jwt/exception/JwtEntryPoint.java
- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> Feat : 마이페이지 프로필 수정,로그아웃 구현

- src/main/java/com/example/catchroom_be/domain/user/controller/mypage/MyPageController.java
- src/main/java/com/example/catchroom_be/domain/user/controller/user/MeController.java
- src/main/java/com/example/catchroom_be/domain/user/entity/User.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeAccessTokenService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeLoginService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageLogOutService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageProfileService.java
- src/main/java/com/example/catchroom_be/global/config/RedisConfig.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
- src/main/java/com/example/catchroom_be/global/jwt/config/JwtFilterConfig.java
- src/main/java/com/example/catchroom_be/global/jwt/dto/JwtPayload.java
- src/main/java/com/example/catchroom_be/global/jwt/dto/RefreshToken.java
- src/main/java/com/example/catchroom_be/global/jwt/exception/JwtEntryPoint.java
- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
- src/main/resources/application.yml
> Feat : 마이페이지 로그아웃,프로필 수정 API 개발 완료

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomInfoResponse.java
- src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
- src/main/java/com/example/catchroom_be/domain/chatroom/exception/ChatRoomException.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomInfoService.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
- src/main/java/com/example/catchroom_be/domain/user/controller/MeController.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
채팅방 내부 정보 조회하는 API 만들었습니다. 
[노션 링크](https://www.notion.so/v1-chat-room-roomId-f9071b06d9b14419a0c50654e573fb8b)
어떤 변경 사항이 있나요?
> Feature/#46 채팅방 내부 정보 조회

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/example/catchroom_be/domain/chatroom/dto/request/ChatRoomCreateRequest.java
- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomCreateResponse.java
- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomGetUnique.java
- src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeAccessTokenService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeLoginService.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- createRoomId 로직 이전
- 객체 매핑 적용
어떤 변경 사항이 있나요?
> Refactor : 채팅방 생성 로직 이전(채팅서버 -> 메인서버)

- src/main/java/com/example/catchroom_be/global/config/CorsConfig.java
> Refact : CORS 수정

- src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
- src/main/java/com/example/catchroom_be/global/config/CorsConfig.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
> Refact : 충돌나는 부분 일시 주석처리

- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageLogOutService.java
- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> Refact : 로그아웃 로직 수정

- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
> fix : spring security config 핫픽스

- src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleEditRequest.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleGetAllInfoResponse.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleGetYanoljaReservationResponse.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/exception/ProductException.java
- src/main/java/com/example/catchroom_be/domain/product/exception/SaleException.java
- src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeAccessTokenService.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeLoginService.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
- ErrorCode 등록 완료 & 기타 예외처리 완료
- 상품 수정 시 기존 등록된 Product 정보 전달하는 API 개발 완료
- JWT accessToken 유효기간 30분으로 수정
어떤 변경 사항이 있나요?
> Feat : 상품 수정 시 기존 정보 전달 API & 예외처리 완료

- src/main/java/com/example/catchroom_be/domain/user/controller/mypage/MyPageController.java
- src/main/java/com/example/catchroom_be/domain/user/entity/User.java
- src/main/java/com/example/catchroom_be/domain/user/repository/UserEntityRepository.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageAccountService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageProfileService.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
> Feat : 예치금 삭제/수정 개발

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
- src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
- 현재 로그인된 사용자별로 포함된 채팅방 리스트 조회
어떤 변경 사항이 있나요?
> Feat : 채팅방 리스트 조회 API 개발

- src/main/java/com/example/catchroom_be/domain/user/controller/mypage/MyPageController.java
> Refact : 엔드포인트 수정

- src/main/java/com/example/catchroom_be/domain/user/controller/mypage/MyPageController.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/LoginResponse.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/ProfileResponse.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageProfileService.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
> Refact : 엔드포인트 및 내용 수정

- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> Refact : accesstoken 테스트

- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
- ResponseDto에서 반환
어떤 변경 사항이 있나요?
> Feat : 채팅방 리스트 반환 시 숙소사진과 채팅상대 닉네임 포함 반환

- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> 토큰 시간 30분 수정 

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
> Feat : Feign API 개발

- src/main/java/com/example/catchroom_be/domain/user/controller/mypage/MyPageController.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/DepositResponse.java
- src/main/java/com/example/catchroom_be/domain/user/entity/DepositDetails.java
- src/main/java/com/example/catchroom_be/domain/user/entity/User.java
- src/main/java/com/example/catchroom_be/domain/user/repository/DepositDetailsRepository.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageAccountService.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
> Feat : 예치금 상세 조회/출금 개발 완료

- src/main/java/com/example/catchroom_be/domain/orderhistory/dto/OrderHistoryCandidateResponse.java
> Feat : 판매숙박권조회 시 매물이름 전달

- src/main/java/com/example/catchroom_be/domain/user/dto/response/DepositResponse.java
- src/main/java/com/example/catchroom_be/domain/user/entity/DepositDetails.java
- src/main/java/com/example/catchroom_be/domain/user/enumlist/DepositType.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageAccountService.java
> Refact : Enum 타입 변경

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
- src/main/java/com/example/catchroom_be/domain/chatroom/type/ChatRoomState.java
> Feat : 채팅방 삭제

- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> Refact : 토큰 테스트 시간 변경

- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> Refact : 토큰 시간 수정

- src/main/java/com/example/catchroom_be/domain/wish/controller/WishController.java
- src/main/java/com/example/catchroom_be/domain/wish/entity/Wish.java
- src/main/java/com/example/catchroom_be/domain/wish/repository/WishRepository.java
- src/main/java/com/example/catchroom_be/domain/wish/service/WishService.java
- src/main/java/com/example/catchroom_be/domain/wish/service/WishServiceImpl.java
> Feature/#35상품 찜하기

- src/main/java/com/example/catchroom_be/domain/accommodation/entity/Accommodation.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/user/entity/User.java
> Refact: 엔티티 수정

- src/main/java/com/example/catchroom_be/domain/buyhistory/controller/BuyHistoryController.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/dto/request/BuyRequest.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/dto/request/PaymentRequest.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PaymentResponse.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PurchaseDetailResponse.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/entity/BuyHistory.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/repository/BuyHistoryRepository.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryService.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
> Feature#37상품 구매하기

- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> Refact : 토큰 테스트

- src/main/java/com/example/catchroom_be/domain/user/dto/response/DepositAccountNumResponse.java
> Refact : 예금주/은행명 추가

- src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductSearchListResponse.java
- src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryCustom.java
- src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
- src/main/java/com/example/catchroom_be/domain/product/service/ProductSearchService.java
> Feature/#29 검색상품조회수정

- src/main/java/com/example/catchroom_be/CatchRoomBeApplication.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
- src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/DepositAccountNumResponse.java
- src/main/java/com/example/catchroom_be/domain/user/entity/Account.java
- src/main/java/com/example/catchroom_be/domain/user/entity/User.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageAccountService.java
- SaleScheduleService 내 크론 적용중
- 상품 구매 시 판매자 balance에 판매가격 적용
어떤 변경 사항이 있나요?
> Feat : 캐치특가 및 상품종료 날짜 스케줄링 적용

- src/main/java/com/example/catchroom_be/domain/product/controller/MainController.java
- src/main/java/com/example/catchroom_be/domain/product/repository/MainRepository.java
- src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustom.java
- src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
- src/main/java/com/example/catchroom_be/domain/product/service/MainService.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
> Feature/#26 메인홈에 보여지는 상품 리스트

- src/main/java/com/example/catchroom_be/domain/product/controller/MainController.java
- src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
- src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustom.java
- src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
- src/main/java/com/example/catchroom_be/domain/product/service/MainService.java
> Fix: 페이지네이션 오류 수정

- src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/repository/ProductRepository.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
- SaleScheduleService 내 크론 적용완료
- 매일 0시 캐치특가 자동적용 로직 개발
- 매분 0초 판매종료 자동적용 로직 개발
어떤 변경 사항이 있나요?
> Feat : 캐치특가 및 상품종료 날짜 스케줄링 적용 API 개발

- src/main/java/com/example/catchroom_be/domain/product/controller/MainController.java
- src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
- src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustom.java
- src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
- src/main/java/com/example/catchroom_be/domain/product/service/MainService.java
> feat : 캐치특가 자동 설정 및 종료날짜 스케줄링 적용

- src/main/java/com/example/catchroom_be/domain/accommodation/entity/AccommodationImage.java
- src/main/java/com/example/catchroom_be/domain/accommodation/entity/Room.java
- src/main/java/com/example/catchroom_be/domain/accommodation/entity/RoomImage.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
- src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
- 캐치 특가 등록 시 상품 게시 마감 이전으로 등록하지 않는 경우 에러 처리
어떤 변경 사항이 있나요?
> refactor : 캐치 특가 등록 시 예외처리 개선

- src/main/java/com/example/catchroom_be/domain/user/entity/User.java
> HotFix: NullPointException 오류 수정

- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomInfoResponse.java
- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
- 채팅서버로 채팅방 리스트 전달 시 dealState 포함
어떤 변경 사항이 있나요?
> refactor : 채팅방 전체 리스트 전달 시 상품 판매 상태 값 추가

- src/main/java/com/example/catchroom_be/domain/user/entity/User.java
> refactor : 채팅방 리스트 전달 시 상품 상태값 포함하여 전달

- src/main/java/com/example/catchroom_be/domain/buyhistory/repository/BuyHistoryRepository.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/repository/OrderHistoryRepository.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/repository/ProductRepository.java
- src/main/java/com/example/catchroom_be/domain/user/controller/mypage/MyPageController.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/SalesHistoryDoneResponse.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/SalesHistoryNowResponse.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageBuyHistoryService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageSalesHistoryService.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
> Feat : 마이페이지 판매내역 개발

- src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
- src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
- 회원 가입 시 야놀자 매물 자동 생성 완료
어떤 변경 사항이 있나요?
> refactor : 회원가입 시 야놀자 구매 내역 매물 자동 생성

- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleEditRequest.java
- src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleEditResponse.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleRegistResponse.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- Product의 is_Deleted 칼럼 T/F로 구분
어떤 변경 사항이 있나요?
> refactor : 상품 삭제 시 SoftDelete로 변경

- src/main/java/com/example/catchroom_be/domain/buyhistory/entity/BuyHistory.java
- src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
- src/main/java/com/example/catchroom_be/domain/review/entity/Review.java
- src/main/java/com/example/catchroom_be/domain/review/enumlist/ReviewDeleteType.java
- src/main/java/com/example/catchroom_be/domain/review/enumlist/ReviewRefactType.java
- src/main/java/com/example/catchroom_be/domain/review/enumlist/ReviewType.java
- src/main/java/com/example/catchroom_be/domain/review/repository/ReviewEntityRepository.java
- src/main/java/com/example/catchroom_be/domain/user/controller/mypage/MyPageController.java
- src/main/java/com/example/catchroom_be/domain/user/dto/request/ReviewPostRequest.java
- src/main/java/com/example/catchroom_be/domain/user/dto/request/ReviewRefactRequest.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/PurChaseHistoryResponse.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/ReviewResponse.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/SalesHistoryDoneResponse.java
- src/main/java/com/example/catchroom_be/domain/user/entity/User.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPagePurchaseHistoryService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageReviewService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageSalesHistoryService.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
> Feat : 마이페이지 리뷰 개발

- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageReviewService.java
> Refact : 생성시간 변경

- src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
> refactor : 상품 구매 시 예치금 적립 api 개발

- src/main/java/com/example/catchroom_be/domain/buyhistory/entity/BuyHistory.java
> Refact : 불필요한 코드 삭제

- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
> Style :채팅 룸 삭제  log 추가

- src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepository.java
> 채팅방 삭제 Log 추가 

- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
> fix : userID equals 수정

- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
> 채팅 룸 정렬 방식 수정 

- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleRegistResponse.java
- productId로 반환
어떤 변경 사항이 있나요?
> refactor : 숙소 등록 시 id 값 함께 반환

- src/main/java/com/example/catchroom_be/domain/product/repository/ProductRepository.java
- src/main/java/com/example/catchroom_be/domain/user/controller/mypage/MyPageController.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/WishResponse.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageWishService.java
- src/main/java/com/example/catchroom_be/domain/wish/repository/WishRepository.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
> Feat : 찜 조회/삭제 개발

- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
> fix : ChatRoomRepositoryCustomImpl 수정

- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
> fix : ChatRoomRepositoryCustomImpl 수 - import 제거

- src/main/java/com/example/catchroom_be/domain/user/dto/response/SalesHistoryDoneResponse.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPagePurchaseHistoryService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageSalesHistoryService.java
> Refact : 리뷰 로직 수정

- src/main/java/com/example/catchroom_be/domain/accommodation/entity/AccommodationImage.java
- src/main/java/com/example/catchroom_be/domain/accommodation/entity/RoomImage.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
- 순환참조 방지로 숙소/룸 엔티티에 @JsonIgnore 활용
어떤 변경 사항이 있나요?
> refactor : 상품 상세 페이지 조회 시 사진 리스트 조회 로직 개선

- src/main/java/com/example/catchroom_be/domain/user/dto/response/SalesHistoryDoneResponse.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPagePurchaseHistoryService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageSalesHistoryService.java
- 사진 조회 시 list 전달
어떤 변경 사항이 있나요?
> Refactor : 상품 상세 페이지 조회 개선

- src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
- UNSOLD로 처리
- 구매 시 상품 endDate 구매 시점으로 업데이트
어떤 변경 사항이 있나요?
> Feat : 매일 15시 체크인 지난 매물 DealState 스케줄링(크론 조건식 수정)

- src/main/java/com/example/catchroom_be/domain/user/dto/response/PurChaseHistoryResponse.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/SalesHistoryDoneResponse.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/SalesHistoryNowResponse.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPagePurchaseHistoryService.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageSalesHistoryService.java
> Refact : 마이페이지 productId 추가

- src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductSearchListResponse.java
결과에 region 추가하였습니다!
어떤 변경 사항이 있나요?
> fix : 검색 결과에 region 추가

- src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleEditResponse.java
- src/main/java/com/example/catchroom_be/domain/product/repository/ProductRepository.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
- roomService 칼럼 삭제
어떤 변경 사항이 있나요?
> Feat : 상품 상세페이지 응답 시 숙소서비스 배열로 응답

- src/main/java/com/example/catchroom_be/domain/user/dto/response/SalesHistoryDoneResponse.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/WishResponse.java
> Refact : 오타수정

- src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
> HotFix : 야놀자 구매 상품이 없을 시 응답 코드 반환 에러 fix

- src/main/java/com/example/catchroom_be/domain/user/dto/response/DepositResponse.java
> Refact : 불필요한 주석 제거

- src/main/java/com/example/catchroom_be/domain/user/dto/response/DepositResponse.java
> HotFix : endDate 체크 주기 변경

- src/main/resources/application.yml
> Feat : 커넥션 

- src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
> Fix : main 브랜치 복구

- src/main/java/com/example/catchroom_be/global/config/CorsConfig.java
- src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
- src/main/java/com/example/catchroom_be/global/jwt/config/JwtFilterConfig.java
> Refact : sercurity 오류 수정

- src/main/java/com/example/catchroom_be/domain/user/controller/user/MeController.java
- src/main/java/com/example/catchroom_be/domain/user/service/me/MeAccessTokenService.java
- src/main/java/com/example/catchroom_be/global/config/CorsConfig.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> Refact : 토큰 시간 변경

- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageReviewService.java
> Refact : 기본값 설정

- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleGetAllInfoResponse.java
> Fix : Price 수정

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
채팅방 내부 정보 api 추가 
어떤 변경 사항이 있나요?
> feat : 채팅방 내부 정보 api 추가

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
- src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleGetAllInfoResponse.java
> 채팅방 내부 정보 api 배포 

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
> fix : api 수정

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
> 채팅방 정보 가져오기 api 수정 및 배포 

- build.gradle
- src/test/java/com/example/catchroom_be/domain/user/service/me/MeLogOutServiceTest.java
- src/test/java/com/example/catchroom_be/domain/user/service/me/MeRegisterServiceTest.java
> Feat : 단위 테스트 코드 작성

- build.gradle
- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/test/java/com/example/catchroom_be/domain/user/service/me/MeLogOutServiceTest.java
- src/test/java/com/example/catchroom_be/domain/user/service/me/MeRegisterServiceTest.java
> Feat : 회원 단위 테스트 코드 작성

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
채팅방 내부 정보 불러오기 수정 
어떤 변경 사항이 있나요?
> fix : api info 추가 수정 2

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
> 채팅방 내부 정보 불러오기 수정 

- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
> fix : api info 추가 수정 3 제발 되라

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
> fix : info 테스트 api

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
> 채팅방 내부 정보 불러오기 api 

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
> fix : 채팅방 내부 정보 불러오기 초기화

- src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
> 채팅방 불러오기 마지막 배포 (원상태 복귀)

- src/main/java/com/example/catchroom_be/domain/user/dto/response/PurChaseHistoryResponse.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPagePurchaseHistoryService.java
> Refact : 구매내역 아이디 추가

- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageSalesHistoryService.java
> Refact : 테스트

- README.md
- src/main/java/com/example/catchroom_be/domain/user/dto/response/ProfileResponse.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/ReviewResponse.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageReviewService.java
> Refact : 반환 타입 수정

- src/main/java/com/example/catchroom_be/domain/user/dto/response/ProfileResponse.java
- src/main/java/com/example/catchroom_be/domain/user/dto/response/ReviewResponse.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageReviewService.java
> 배포 : 판매 가능한 상품만 보여지도록 수정 

- src/main/java/com/example/catchroom_be/domain/user/dto/response/WishResponse.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageWishService.java
> Refact : 응답 수정

- src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
- src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
- isWishChecked 칼럼 추가
어떤 변경 사항이 있나요?
> Fix : 상품 상세페이지 조회 시 찜 클릭 여부 추가

- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> Refact : 토큰 테스트 시간 수저

- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> Refact : 테스트 토큰 시간 수정

- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
버그를 수정하기 위해 
채팅방에 내 닉네임도 전달되도록 수정하였습니다. 
어떤 변경 사항이 있나요?
> fix : 채팅방에 내 닉네임도 전달되도록 수정

- src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
> 채팅방 전송시 내 닉네임도 보이도록 수정 

- src/main/java/com/example/catchroom_be/domain/accommodation/entity/Accommodation.java
- src/main/java/com/example/catchroom_be/domain/accommodation/type/RegionUtil.java
지역명을 충청남도 -> 충북식으로 통일하였습니다. 
어떤 변경 사항이 있나요?
> fix : 지역명 충청남도 -> 충북 식으로 수정

- src/main/java/com/example/catchroom_be/domain/accommodation/entity/Accommodation.java
- src/main/java/com/example/catchroom_be/domain/accommodation/type/RegionUtil.java
- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
> 지역명 수정 후 배포 

- src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
> fix : 채팅방 응답 메시지에 isNego 포함.

- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
- 판매 종료 날짜를 현시점보다 이전으로 등록 시 에러
- 판매 종료 날짜를 체크인 날짜 이후로 등록 시 에러
- 캐치 특가 자동 설정 시점을 현시점보다 이전으로 등록 시 에러
- 캐치 특가 자동 설정 시점을 판매 종료 날짜 이후로 등록 시 에러
- 체크인 날짜가 지난 상품은 수정 페이지 접근 불가
- 이미 삭제된 상품은 수정 페이지 접근 불가
어떤 변경 사항이 있나요?
> Fix : 상품 등록, 수정 시 에러메세지 세분화

- src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
- src/main/java/com/example/catchroom_be/domain/product/type/DealState.java
- SaleSchedulerService 업데이트
어떤 변경 사항이 있나요?
> Fix : 체크인날짜가 지난 경우 UNABLESELL enum 추가

- src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
- src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepositoryImpl.java
메인홈, 이용후기 정렬 로직을 수정하였습니다. 
어떤 변경 사항이 있나요?
> fix : 메인홈, 이용후기 정렬 로직 추가 및 수정

- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
- endDate가 현시점 이전인 경우로 변경
어떤 변경 사항이 있나요?
> Fix : 상품수정 시 DealState 업데이트 코드 정리

- src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustom.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
채팅방 생성시 중복 생성 안되게 로직을 수정하였습니다. 
어떤 변경 사항이 있나요?
> fix : 채팅방 중복 생성 안되게 수정

- src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustom.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
- src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
채팅방 중복 생성 안되게 로직을 수정하였습니다. 
어떤 변경 사항이 있나요?
> Fix : 채팅방 중복 생성 안되게 로직을 수정

- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageWishService.java
fix : 구매 가격 - 야놀자 구매 가격에서 수정하였습니다. 
어떤 변경 사항이 있나요?
> fix : 구매 가격 - 야놀자 구매 가격에서 수정

- src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
- src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
- src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
메인홈, 검색시 총갯수랑 리스트 갯수 안 맞는거 수정하였습니다. 
어떤 변경 사항이 있나요?
> fix : 총갯수 유령갯수 수정

- README.md
- src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
- src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
- src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
- src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageWishService.java
> Fix : 상품 리스트 조회시 총갯수와 실제 리스트 갯수 동일하게 변경 

- src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PaymentResponse.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PurchaseDetailResponse.java
- src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
> HotFix: 구매자 닉네임 추가

- src/main/java/com/example/catchroom_be/domain/chatroom/dto/request/ChatRoomCreateRequest.java
- src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustom.java
- src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
- src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
- QueryDSL 에서 JPA로 변경
- ChatService if문 가독성 확보
어떤 변경 사항이 있나요?
> Refactor : createChatRoom 시 JPA 활용
